### ISSUE TITLE
To-do list for VLB analysis

### ISSUE THREAD

**Issue by bpbond** [bpbond/dwp_injection#14]
- [ ] update code and clean up
- [ ] deal with outliers etc.
- [ ] time on x, evolved C on y, facets are depth ~ site
- [ ] cumulative C numbers (by gas and total)

**Comment by bpbond** [comment]
The big thing here, now, is the cumulative net fluxes. Do this once other issues ( #16 and #20 ) are resolved.
